# Generated by Django 2.1.4 on 2019-04-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopledetail',
            name='headshot',
            field=models.ImageField(default='/personimage/default.png', upload_to='personimage'),
        ),
    ]
