# Generated by Django 2.1.4 on 2019-05-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemanager', '0003_auto_20190411_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='degree',
            field=models.CharField(choices=[('MSc', 'MSc'), ('PhD', 'PhD'), ('ERF', 'ERF')], max_length=8),
        ),
    ]
