# Generated by Django 2.2.2 on 2019-06-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemanager', '0004_auto_20190516_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetail',
            name='category',
            field=models.CharField(choices=[('CS', 'Core Staff'), ('RAF', 'Research Associates And Fellows'), ('PDRF', 'Postdoctoral Research Fellow'), ('S', 'Students')], max_length=200),
        ),
    ]
