# Generated by Django 2.2.2 on 2019-06-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemanager', '0006_staffdetail_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetail',
            name='qualification',
            field=models.CharField(blank=True, choices=[('BCom', 'BCom'), ('BTech', 'BTech'), ('BSc', 'BSc'), ('Hons', 'Hons'), ('Mtech', 'Mtech'), ('MBA', 'MBA'), ('MSc', 'MSc'), ('PhD', 'PhD')], max_length=8, null=True),
        ),
    ]
