# Generated by Django 2.2.2 on 2019-06-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemanager', '0008_auto_20190624_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetail',
            name='category',
            field=models.CharField(choices=[('CS', 'Core Staff'), ('RAF', 'Research Associates And Fellows'), ('PDRF', 'Postdoctoral Research Fellow'), ('S', 'Students'), ('SC', 'Steering Committee')], max_length=200),
        ),
    ]
