# Generated by Django 2.2.2 on 2019-06-27 15:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemanager', '0010_staffdetail_research_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetail',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CS', 'Core Staff'), ('RAF', 'Research Associates And Fellows'), ('PDRF', 'Postdoctoral Research Fellow'), ('S', 'Students'), ('SC', 'Steering Committee')], max_length=16),
        ),
    ]
