# Generated by Django 2.2.2 on 2019-06-27 16:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemanager', '0011_auto_20190627_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetail',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CS', 'Core Staff'), ('RAF', 'Research Associates And Fellows'), ('PDRF', 'Postdoctoral Research Fellow'), ('SC', 'Steering Committee')], max_length=14),
        ),
    ]
