# Generated by Django 2.2.2 on 2019-07-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemanager', '0012_auto_20190627_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='degree',
            field=models.CharField(choices=[('MSc', 'MSc'), ('PhD', 'PhD'), ('ERF', 'ERF'), ('Hons', 'Hons')], max_length=8),
        ),
    ]
