# Generated by Django 2.2.2 on 2019-07-18 14:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('peoplemanager', '0014_auto_20190715_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetail',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CS', 'Core Staff'), ('RAF', 'Research Associates And Fellows'), ('PDRF', 'Postdoctoral Research Fellow'), ('SC', 'Steering Committee'), ('SUSAC', 'Scientific Advisory Committee')], max_length=20),
        ),
    ]
