# Generated by Django 2.1.4 on 2019-01-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarevents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='eventtype_id',
            new_name='EventType',
        ),
    ]
