# Generated by Django 2.1.4 on 2019-01-27 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendarevents', '0002_auto_20190127_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='EventType',
            new_name='Event_Type',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='urllink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
