# Generated by Django 2.1.4 on 2019-01-28 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarevents', '0003_auto_20190127_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name_plural': 'Calendar'},
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Event_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='calendarevents.EventType'),
        ),
    ]
