from django.db import models
# Create your models here.
class Tsetse(models.Model):
	caseno = models.IntegerField(null=True, blank=True,verbose_name=('caseno2'))
	vpn  = models.IntegerField(null=True, blank=True,verbose_name=('vpn'))
	vol  = models.IntegerField(null=True, blank=True,verbose_name=('Volume'))
	pg	 = models.IntegerField(null=True, blank=True,verbose_name=('Page'))
	no	 = models.IntegerField(null=True, blank=True,verbose_name=('Number on page'))
	cd	 = models.IntegerField(null=True, blank=True,verbose_name=('Capture day of month'))
	cm	 = models.IntegerField(null=True, blank=True,verbose_name=('Capture month of year'))
	cy	 = models.IntegerField(null=True, blank=True,verbose_name=('Capture Year'))
	expmon	 = models.IntegerField(null=True, blank=True,verbose_name=('Experimental Month'))
	dayj = models.IntegerField(null=True, blank=True,verbose_name=('Capture days since 01-01-1960'))
	di = models.IntegerField(null=True, blank=True,verbose_name=('Dissector Code'))
	m = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Microscope'))
	site = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Capture Sites'))
	md = models.IntegerField(null=True, blank=True,verbose_name=('Capture Method code'))
	tst = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Capture start time'))
	tend = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Capture end time')) # to be reviewed
	dd = models.IntegerField(null=True, blank=True,verbose_name=('Dissection day'))
	dm = models.IntegerField(null=True, blank=True,verbose_name=('Dissection month'))
	t = models.IntegerField(null=True, blank=True,verbose_name=('Time of dissection - am/pm')) #can be reviewd
	genus= models.IntegerField(null=True, blank=True,verbose_name=('Genus'))
	sex= models.IntegerField(null=True, blank=True,verbose_name=('Sex'))
	al=  models.IntegerField(null=True, blank=True,verbose_name=('al Largest oocyte length - mm x 100'))
	ad = models.IntegerField(null=True, blank=True,verbose_name=('ad Largest oocyte diameter - mm x 100'))
	bl = models.CharField(max_length=50,null=True, blank=True,verbose_name=('bl 2nd largest oocyte diameter -mm x 100'))
	bd = models.CharField(max_length=50,null=True, blank=True,verbose_name=('bd 2nd largest oocyte diameter - mm x 100'))
	c = models.IntegerField(null=True, blank=True,verbose_name=('Ovarian Category'))
	u = models.IntegerField(null=True, blank=True,verbose_name=('uterine content'))
	ulm= models.IntegerField(null=True, blank=True,verbose_name=('ulm Uterine length - mm x 100'))
	udm= models.IntegerField(null=True, blank=True,verbose_name=('udm Uterine length - mm x 100'))
	sl= models.IntegerField(null=True, blank=True,verbose_name=('Left spermatophore content 0-10'))
	sr= models.IntegerField(null=True, blank=True,verbose_name=('Right spermatophore content 0-10'))
	h = models.IntegerField(null=True, blank=True,verbose_name=('Hunger stage'))
	wl = models.IntegerField(null=True, blank=True,verbose_name=('Wing length - scale'))
	wlm = models.IntegerField(null=True, blank=True,verbose_name=('Wing length - mm x 100'))
	facwlmnew = models.CharField(max_length=50,null=True, blank=True,verbose_name=('facwlmnew'))
	wlm2 = models.IntegerField(null=True, blank=True,verbose_name=('Wing length - mm x 100'))
	f= models.IntegerField(null=True, blank=True,verbose_name=('Wing fray 1-6'))
	d = models.IntegerField(null=True, blank=True,verbose_name=('Determinant for pregancy stage'))
	ppr = models.IntegerField(null=True, blank=True,verbose_name=('Percent pregnancy completed'))
	ilp= models.IntegerField(null=True, blank=True,verbose_name=('Inter-larval period'))
	pd= models.IntegerField(null=True, blank=True,verbose_name=('Estimated day of pregnancy'))
	age= models.IntegerField(null=True, blank=True,verbose_name=('Estimated age - days'))
	bday= models.IntegerField(null=True, blank=True,verbose_name=('Estimated birth day - Julian'))
	alm= models.IntegerField(null=True, blank=True,verbose_name=('Cut-off al length for deciding if fly aborted'))
	e1 = models.IntegerField(null=True, blank=True,verbose_name=('Error code 1'))
	e2 = models.IntegerField(null=True, blank=True,verbose_name=('Error code 2'))
	r = models.IntegerField(null=True, blank=True,verbose_name=('r=1 if dissector has noted problem, r=0 otherwise'))
	tube= models.IntegerField(null=True, blank=True,verbose_name=('Tube number'))
	tubet= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Alphanumeric label for tube'))
	pt= models.IntegerField(null=True, blank=True,verbose_name=('Pteridine???'))
	trdw=  models.IntegerField(null=True, blank=True,verbose_name=('Mothers thoracic resid. dry weight')) # requires review
	mk= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Mark'))
	vol = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Uterine volume'))
	dwu= models.CharField(max_length=50,null=True, blank=True,verbose_name=('DWU'))
	rdwu= models.CharField(max_length=50,null=True, blank=True,verbose_name=('RDWU'))
	fatu= models.CharField(max_length=50,null=True, blank=True,verbose_name=('FATU'))
	fwu= models.CharField(max_length=50,null=True, blank=True,verbose_name=('FWU'))
	tr= models.CharField(max_length=50,null=True, blank=True,verbose_name=('TR'))
	dw = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Mothers dry weight'))
	rdw = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Mothers resid. dry weight'))
	fat = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Mothers fat weight'))
	ardw = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Mothers abdominal resid. dry weight')) # requires review
	haem = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Mothers haematin')) #requires review
	totdw = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Mother+pupa dry weight'))
	totrdw = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Mother+pupa resid. dry weight'))
	totfat= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Mother+pupa fat weight'))
	edwu= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Uterine dry weight - est. from volume'))
	erdwu= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Uterine resid. dry weight - est. from volume'))
	efatu = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Uterine fat weight - est. from volume'))
	efwu = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Uterine fresh weight - est. from volume'))
	lpm= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Puparial length - mm x 100'))#requires review
	dpm= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Puparial length - mm x 100'))# requires review
	volp= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Uterine volume'))
	dwp= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Puparial dry weight'))
	rdwp= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Puparial resid. dry weight'))
	fatp= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Puparial fat weight'))
	fatp0= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Puparial fat weight - corrected for process delay'))
	fwp= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Puparial fresh weight'))
	edwp= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Puparial dry weight - est. from volume'))
	erdwp= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Puparial resid. dry weight - est. from volume'))
	efatp= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Puparial fat weight - est. from volume'))
	efwp= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Puparial fresh weight - est. from volume'))
	fd= models.CharField(max_length=50,null=True, blank=True)
	fjd= models.CharField(max_length=50,null=True, blank=True)
	idd= models.CharField(max_length=50,null=True, blank=True,verbose_name=('id'))# column name to be reviewd
	im= models.CharField(max_length=50,null=True, blank=True)
	ijd= models.CharField(max_length=50,null=True, blank=True)
	ep= models.CharField(max_length=50,null=True, blank=True)
	mx= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Presence of adult'))
	px= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Presence of pupa'))
	totfat0= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Mother+pupa ??????'))
	etotdw = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Estimated mother+pupa dry weight'))
	etotrdw = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Estimated mother+pupa resid. dry weight'))
	etotfat= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Estimated mother+pupa fat weight'))
	bt= models.CharField(max_length=50,null=True, blank=True,verbose_name=('BT'))
	cms= models.CharField(max_length=50,null=True, blank=True ,verbose_name=('Capture month of experiment'))
	bm2= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Birth month??? Different definition from bm: check'))
	bm= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Birth month'))
	by= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Birth year'))
	bms= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Birth month for female born in month cms CAREFUL'))
	sitep= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Pooled Capture sites'))
	mdp= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Pooled capture methods'))
	age0= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Estimated age - negatives changed to 0 '))
	dy= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Year of dissection'))
	del1= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Days delay in dissection')) #tobe reviewd as clomun is del in source data
	slr = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Sperm: left plus right'))
	slrp= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Total sperm: pooled units 4'))
	slrp2 = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Tot sperm: pooled 0, 1-8, 9-16, 17-20'))
	dofy = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Day of the year'))
	dofy9 = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Day of the year: 9-day pool'))
	pyri = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Pyriproxyfen traps/targets used'))
	mdpall = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Methods pooled major'))
	log10hm = models.CharField(max_length=50,null=True, blank=True,verbose_name=('log10 of haematin in nanograms'))
	cnu = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Ovcat where ppp flies with u=0 put into next ovcat'))
	ftpp = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Full term, ppp, pregnant etc'))
	ftppp = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Full term, ppp, pregnant etc'))
	ppall= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Full term, ppp, pregnant etc'))
	pprpl= models.CharField(max_length=50,null=True, blank=True)
	pprpl2= models.CharField(max_length=50,null=True, blank=True)
	runmin9= models.CharField(max_length=50,null=True, blank=True)
	dwmg= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Mothers dry weight (mg)'))# to be reviewed
	rdwmg= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Residual dry weight (mg)'))
	fatmg = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Mothers fat weight (mg'))
	trdwmg = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Mothers thoracic resid. dry weight (mg'))#to be reviewed
	ardwmg = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Mothers abdominal resid. dry weight (mg)'))#to be reviewed
	wlmm = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Wing length (mm)'))
	fwpmg = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Puparial fresh weight (mg)'))
	dwpmg = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Puparial dry weight (mg)'))
	fatpmg = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Puparial fat weight (mg)'))
	rdwpmg = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Puparial resid. dry weight (mg)'))
	totdwmg = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Mother+pupa dry weight (mg)'))
	totrdwmg = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Mother+pupa resid. dry weight (mg)'))
	totfatmg = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Mother+pupa fat weight (mg)'))
	#Column datat types followed
	ctemp = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Ovarian age moving c = 4-7 to 8-11 if f>4'))# column name to be reviewd
	cf56 = models.CharField(max_length=50,null=True, blank=True,verbose_name=('Ovarian category where flies recategorised if f>4'))# column name to be reviewd
	cf6= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Ovarian category where flies recategorised if f>5')) 
	testtem = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True)
	datest= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Date sample started'))
	cctem= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Capture month of year'))
	pgall= models.CharField(max_length=50,null=True, blank=True,verbose_name=('New page numbering'))
	idfly= models.CharField(max_length=50,null=True, blank=True,verbose_name=('Unique number for each fly in file'))
	datecap =models.DateField(null=True, blank=True,verbose_name=('Date sample collected'))
	datedis = models.DateField(null=True, blank=True)
	ndvi = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True,verbose_name=('NDVI on day of capture'))
	ndvi90 = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True,verbose_name=('NDVI Average over 9-days forward from capture day'))
	ndvi91 = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True,verbose_name=('NDVI Average over 9-days backward from capture day'))
	ndvi92 = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True,verbose_name=('NDVI Average over 9-days backward, starting 9 days prior to capture day'))
	ndvi93 = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True,verbose_name=('NDVI Average over 9-days backward, starting 18 days prior to capture day'))
	ndvi94 = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True,verbose_name=('NDVI Average over 9-days backward, starting 27 days prior to capture day'))
	ndvi300 = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True,verbose_name=('NDVI Average over 30-days forward from capture day'))
	ndvi301 = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True,verbose_name=('NDVI Average over 30-days backward from capture day'))
	ndvi302 = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True,verbose_name=('NDVI Average over 30-days backward, starting 30 days prior to capture day'))
	ndvi303 = models.DecimalField(max_digits=25, decimal_places=25, null=True, blank=True,verbose_name=('NDVI Average over 30-days backward, starting 60 days prior to capture day'))
	tmax = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True,verbose_name=('Maximum temp on day of capture'))
	tmax90 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True,verbose_name=('Tmax Average over 9-days forward from capture day'))
	tmax91 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True,verbose_name=('Tmax Average over 9-days backward from capture day'))
	tmax92 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True,verbose_name=('Tmax Average over 9-days backward, starting 9 days prior to capture day'))
	tmax93 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True,verbose_name=('Tmax Average over 9-days backward, starting 18 days prior to capture day'))
	tmax94 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True,verbose_name=('Tmax Average over 9-days backward, starting 27 days prior to capture day'))
	tmin = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True,verbose_name=('Minimum temp on day of capture'))
	tmin90 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True,verbose_name=('Tmin Average over 9-days forward from capture day'))
	tmin91 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True,verbose_name=('Tmin Average over 9-days backward from capture day'))
	tmin92 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True,verbose_name=('Tmin Average over 9-days backward, starting 9 days prior to capture day'))
	tmin93 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True,verbose_name=('Tmin Average over 9-days backward, starting 18 days prior to capture day'))
	tmin94 = models.DecimalField(max_digits=6, decimal_places=3, null=True, blank=True,verbose_name=('Tmin Average over 9-days backward, starting 27 days prior to capture day'))
	tbar = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,verbose_name=('Average of max and min temp on day of capture'))
	tbar90 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,verbose_name=('Tbar Average over 9-days forward from capture day'))
	tbar91 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,verbose_name=('Tbar Average over 9-days backward from capture day'))
	tbar92 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,verbose_name=('Tbar Average over 9-days backward, starting 9 days prior to capture day '))
	tbar93 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,verbose_name=('Tbar Average over 9-days backward, starting 18 days prior to capture day'))
	tbar94 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,verbose_name=('Tbar Average over 9-days backward, starting 27 days prior to capture day'))
	rain = models.DecimalField(max_digits= 6, decimal_places=3, null=True, blank=True,verbose_name=('Total rain on day of capture'))
	
	cf456 = models.IntegerField(null=True, blank=True, verbose_name=('Ovarian category where flies recategorised if f>3'))
	dur = models.IntegerField(null=True, blank=True)
	tbars = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Average temperature Capture day Sensor'))
	tbars90 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,verbose_name=('tbars over 9-day forward from capture day'))
	tbars91 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('tbars over 9-day backward from capture day'))
	tbars92 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('tbars over 9-day backward, starting 9-days prior to capture day'))
	tbars93 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('tbars over 9-day backward, starting 18-days prior to capture day'))
	tbars94 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('tbars over 9-day backward, starting 27-days prior to capture day'))
	rhbars = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Average relative humidity on Capture day Sensor'))
	rhbars90 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('rhbars over 9-day forward from capture day'))
	rhbars91 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,  verbose_name=('rhbars over 9-day backward from capture day'))
	rhbars92 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,  verbose_name=('rhbars over 9-day backward, starting 9-days prior to capture day'))
	rhbars93 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('rhbars over 9-day backward, starting 18-days prior to capture day'))
	rhbars94 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,  verbose_name=('rhbars over 9-day backward, starting 27-days prior to capture day'))
	sdhgbars = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,  verbose_name=('Average Saturation deficit mmHg on Capture day Sensor'))
	sdhgbars90 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('sdhgbars over 9-day forward from capture day'))
	sdhgbars91 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('sdhgbars over 9-day backward from capture day'))
	sdhgbars92 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,  verbose_name=('sdhgbars over 9-day backward, starting 9-days prior to capture day'))
	sdhgbars93 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,  verbose_name=('sdhgbars over 9-day backward, starting 18-days prior to capture day'))
	sdhgbars94 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,  verbose_name=('sdhgbars over 9-day backward, starting 27-days prior to capture day'))

	hmmug = models.CharField(max_length=50,null=True, blank=True,  verbose_name=('Haeamtin content not sure of units'))
	dj= models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,  verbose_name=('Day of experiment rescaled'))
	nf = models.IntegerField(null=True, blank=True,  verbose_name=('Dissected for infection at all 0/1'))
	la = models.CharField(max_length=50,null=True, blank=True, verbose_name=('Infection code for labrum'))
	hp = models.CharField(max_length=50,null=True, blank=True, verbose_name=('Infection code for hypopharynx'))
	sg = models.CharField(max_length=50,null=True, blank=True, verbose_name=('Infection code for salivary glands'))
	mg = models.CharField(max_length=50,null=True, blank=True,  verbose_name=('Infection code for midgut'))
	la2 = models.IntegerField(null=True, blank=True,  verbose_name=('Infection 0/1 for labrum'))
	hp2 = models.IntegerField(null=True, blank=True,  verbose_name=('Infection 0/1 for hypopharynx'))
	mpart = models.IntegerField(null=True, blank=True,  verbose_name=('Infection 0/1 for any mouthpart tryps'))
	mg2 = models.IntegerField(null=True, blank=True,  verbose_name=('Infection 0/1 for midgut'))
	vivax = models.IntegerField(null=True, blank=True,  verbose_name=('Infection 0/1 for vivax'))
	sg2 = models.IntegerField(null=True, blank=True,  verbose_name=('Infection 0/1 for salivary glands'))
	congo = models.IntegerField(null=True, blank=True, verbose_name=('Infection 0/1 for congo'))
	brucei = models.IntegerField(null=True, blank=True, verbose_name=('Infection 0/1 for brucei'))
	brucong = models.IntegerField(null=True, blank=True, verbose_name=('Infection 0/1 for mixed congo/brucei'))
	fatppcg= models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Measured percent fat in pupa: fatp/dwp'))
	efatp2 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Pupal fat estimated as 32% of pupal dry weight'))
	etotfat2 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Mother fat + pupal fat as 32% of DWP'))
	eggooc = models.IntegerField(null=True, blank=True, verbose_name=('Egg or oocyte length for flies in ftpp 16 or 17'))
	abort = models.IntegerField(null=True, blank=True, verbose_name=('Abort=1 if e1=31-33 0 otherwise'))
	tbar91p = models.IntegerField(null=True, blank=True, verbose_name=('Pooled running mean prev 9-days'))
	cm2 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True , verbose_name=('Fortnightly time intervals'))
	umt = models.IntegerField(null=True, blank=True, verbose_name=('Equals 1 if uterus empty, zero if full'))
	tbar91sq = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True , verbose_name=('Quadratic (tbar91^2)/30'))
	fatppcprdw = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Measured pupal fat as percent of pupal RDW'))
	fatpcrdw =models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,  verbose_name=('Maternal postpartum fat divided by RDW'))
	propfat = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Pupal fat as proportion of total fat: efatp2/etotfat2'))
	fatproptrdw = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Maternal postpartum fat divided by TRDW'))
	fatranspc = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Percent of mothers fat transfered to pupa'))
	etotfat2sq = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('etotfat2 squared') )
	date = models.DateField(null=True, blank=True)
	windv = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Wind velocity m/s'))
	windv9 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Wind vel average over prior 9 days'))
	soiltem = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Soil temp degrees C'))
	soiltem9 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Soil temp average over prior 9days'))
	radiation = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True, verbose_name=('Black body radiation degrees C'))
	rad9 = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True,verbose_name=('Black body radiation average over prior 9 days'))
	bday9 = models.IntegerField(null=True, blank=True,verbose_name=('Birthday in 9 day groups'))
	bdaydate = models.DateField(null=True, blank=True, verbose_name=('Birthday formatted as date'))
	bmon = models.IntegerField(null=True, blank=True, verbose_name=('Month of the year fly emerged as teneral'))
	wlmpl = models.IntegerField(null=True, blank=True)
	nfmmg = models.IntegerField(null=True, blank=True, verbose_name=('Mouthparts & midgut BOTH dissected for infection'))
	fsq = models.IntegerField(null=True, blank=True)
	cnusq2 = models.IntegerField(null=True, blank=True,verbose_name=('cnu squared NEW verison Dec 2017'))
	tbarm0 = models.CharField(max_length=50,null=True, blank=True)
	tbarm1 = models.CharField(max_length=50,null=True, blank=True)
	tbarm2 = models.CharField(max_length=50,null=True, blank=True)
	rhm0 = models.CharField(max_length=50,null=True, blank=True)
	rhm1 = models.CharField(max_length=50,null=True, blank=True)
	rhm2 = models.CharField(max_length=50,null=True, blank=True)
	sdefm0 = models.CharField(max_length=50,null=True, blank=True)
	sdefm1 = models.CharField(max_length=50,null=True, blank=True)
	sdefm2 = models.CharField(max_length=50,null=True, blank=True)
	mdpall2 = models.IntegerField(null=True, blank=True,verbose_name=('Methods max pooling nkl'))
	ptpl = models.IntegerField(null=True, blank=True)
	wlmnew = models.CharField(max_length=50,null=True, blank=True)
	facwlmold = models.DecimalField(max_digits=15, decimal_places=10, null=True, blank=True)


	class Meta:
		verbose_name_plural = "Tsetse data"
