# Generated by Django 2.1.4 on 2019-02-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordmanager', '0004_auto_20190206_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': 'Sacema Logins version 2'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sacemaaccounts',
            name='boardroom_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sacemaaccounts',
            name='door_pin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sacemaaccounts',
            name='gmail_course_applications',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sacemaaccounts',
            name='pc_lock',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sacemaaccounts',
            name='sacema_database',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sacemaaccounts',
            name='sacema_webserver',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
