# Generated by Django 2.1.4 on 2019-02-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwordmanager', '0006_auto_20190206_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': ' Accounts, Usernames & Passwords for Sacema '},
        ),
    ]
