# Generated by Django 2.1.4 on 2019-02-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generalenquiries', models.TextField(blank=True, max_length=2000, null=True)),
                ('physicaladdress', models.TextField(blank=True, max_length=2000, null=True)),
                ('postaladdress', models.TextField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
