# Generated by Django 2.1.4 on 2019-02-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generalenquiries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactperson', models.CharField(blank=True, max_length=200, null=True)),
                ('contactemail', models.EmailField(blank=True, max_length=200, null=True)),
                ('tel', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.DeleteModel(
            name='Contactus',
        ),
    ]
