# Generated by Django 2.1.4 on 2019-02-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_auto_20190204_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalenquiries',
            options={'verbose_name_plural': 'General Enquiries'},
        ),
        migrations.RenameField(
            model_name='generalenquiries',
            old_name='tel',
            new_name='contactfax',
        ),
        migrations.AddField(
            model_name='generalenquiries',
            name='contacttelephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
