# Generated by Django 2.1.4 on 2019-02-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_auto_20190204_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physicaladdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physicaladdress', models.TextField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Physical Address',
            },
        ),
        migrations.CreateModel(
            name='Postaladdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postaladdress', models.TextField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Postal Address',
            },
        ),
    ]
