# Generated by Django 2.1.4 on 2019-02-10 11:37

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0005_auto_20190205_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', djgeojson.fields.PointField()),
            ],
        ),
    ]
