# Generated by Django 2.1.4 on 2019-02-20 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0007_auto_20190210_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name_plural': 'Sacema Locations'},
        ),
    ]
