# Generated by Django 2.1.4 on 2019-01-16 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intbursary',
            options={'verbose_name_plural': 'Internal Bursaries'},
        ),
    ]
