# Generated by Django 2.1.4 on 2019-01-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190116_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intbursary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
