# Generated by Django 2.1.4 on 2019-03-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190121_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intbursary',
            name='article',
            field=models.FileField(blank=True, null=True, upload_to='applicantfiles'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='applicantfiles'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='id_copy',
            field=models.FileField(blank=True, null=True, upload_to='applicantfiles'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='personal_statement',
            field=models.FileField(blank=True, null=True, upload_to='applicantfiles'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='ref_letter',
            field=models.FileField(blank=True, null=True, upload_to='applicantfiles'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='applicantfiles'),
        ),
    ]
