# Generated by Django 2.2.2 on 2019-06-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190314_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intbursary',
            name='degree_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Degree 1'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='degree_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Degree 2'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='degree_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Degree 3'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='degree_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Degree 4'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='f_o_study_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Field of study 1'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='f_o_study_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Field of study 2'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='f_o_study_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Field of study 3'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='f_o_study_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Field of study 4'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='institution_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Institution 1'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='institution_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Institution 2'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='institution_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Institution 3'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='institution_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Institution 4'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='major_sub_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Major Subject 1'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='major_sub_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Major subject 2'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='major_sub_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Major subject 3'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='major_sub_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Major subject 4'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='year_obtained_1',
            field=models.CharField(blank=True, max_length=10, verbose_name='Year obtained 1'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='year_obtained_2',
            field=models.CharField(blank=True, max_length=10, verbose_name='Year obtained 2'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='year_obtained_3',
            field=models.CharField(blank=True, max_length=10, verbose_name='Year obtained 3'),
        ),
        migrations.AlterField(
            model_name='intbursary',
            name='year_obtained_4',
            field=models.CharField(blank=True, max_length=10, verbose_name='Year obtained 4'),
        ),
    ]
