# Generated by Django 2.2.2 on 2019-07-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivesuploads', '0002_auto_20190714_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivesuploads',
            name='general_doi',
            field=models.TextField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='archivesuploads',
            name='name',
            field=models.TextField(blank=True, max_length=200000, null=True),
        ),
        migrations.AlterField(
            model_name='archivesuploads',
            name='size',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='archivesuploads',
            name='title',
            field=models.TextField(blank=True, max_length=200000, null=True),
        ),
        migrations.AlterField(
            model_name='archivesuploads',
            name='url',
            field=models.URLField(blank=True, max_length=50000, null=True),
        ),
    ]
