# Generated by Django 2.1.4 on 2019-05-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRAP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsetse',
            name='day_of_experiment_dj',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='dissected_for_infection_at_all_0_or_1_nf',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='infection_0_or_1_for_any_mouthpart_tryps_mpart',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='infection_0_or_1_for_brucei_brucei',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='infection_0_or_1_for_congo_congo',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='infection_0_or_1_for_hypopharynx_hp2',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='infection_0_or_1_for_labrum_la2',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='infection_0_or_1_for_midgut_mg2',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='infection_0_or_1_for_mixed_congo_or_brucei_brucong',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='infection_0_or_1_for_salivary_glands_sg2',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='infection_0_or_1_for_vivax_vivax',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='infection_code_for_hypopharynx_hp',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='infection_code_for_labrum_la',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='infection_code_for_midgut_mg',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='infection_code_for_salivary_glands_sg',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='measured_percent_fat_in_pupa_fatppcg',
        ),
        migrations.AddField(
            model_name='tsetse',
            name='brucei',
            field=models.IntegerField(blank=True, null=True, verbose_name='Infection 0/1 for brucei'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='brucong',
            field=models.IntegerField(blank=True, null=True, verbose_name='Infection 0/1 for mixed congo/brucei'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='congo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Infection 0/1 for congo'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='dj',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Day of experiment rescaled'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='fatppcg',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Measured percent fat in pupa: fatp/dwp'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='hp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Infection code for hypopharynx'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='hp2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Infection 0/1 for hypopharynx'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='la',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Infection code for labrum'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='la2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Infection 0/1 for labrum'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='mg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Infection code for midgut'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='mg2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Infection 0/1 for midgut'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='mpart',
            field=models.IntegerField(blank=True, null=True, verbose_name='Infection 0/1 for any mouthpart tryps'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='nf',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dissected for infection at all 0/1'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='sg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Infection code for salivary glands'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='sg2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Infection 0/1 for salivary glands'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='vivax',
            field=models.IntegerField(blank=True, null=True, verbose_name='Infection 0/1 for vivax'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='abort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Abort=1 if e1=31-33 0 otherwise'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='cf456',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ovarian category where flies recategorised if f>3'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='cm2',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Fortnightly time intervals'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='efatp2',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Pupal fat estimated as 32% of pupal dry weight'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='eggooc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Egg or oocyte length for flies in ftpp 16 or 17'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='etotfat2',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Mother fat + pupal fat as 32% of DWP'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='etotfat2sq',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='etotfat2 squared'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='fatpcrdw',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Maternal postpartum fat divided by RDW'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='fatppcprdw',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Measured pupal fat as percent of pupal RDW'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='fatproptrdw',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Maternal postpartum fat divided by TRDW'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='fatranspc',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Percent of mothers fat transfered to pupa'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='hmmug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Haeamtin content not sure of units'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='mdpall2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Methods max pooling nkl'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='propfat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Pupal fat as proportion of total fat: efatp2/etotfat2'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='rhbars',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Average relative humidity on Capture day Sensor'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='rhbars90',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='rhbars over 9-day forward from capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='rhbars91',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='rhbars over 9-day backward from capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='rhbars92',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='rhbars over 9-day backward, starting 9-days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='rhbars93',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='rhbars over 9-day backward, starting 18-days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='rhbars94',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='rhbars over 9-day backward, starting 27-days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='sdhgbars',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Average Saturation deficit mmHg on Capture day Sensor'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='sdhgbars90',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='sdhgbars over 9-day forward from capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='sdhgbars91',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='sdhgbars over 9-day backward from capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='sdhgbars92',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='sdhgbars over 9-day backward, starting 9-days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='sdhgbars93',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='sdhgbars over 9-day backward, starting 18-days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='sdhgbars94',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='sdhgbars over 9-day backward, starting 27-days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tbar91p',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pooled running mean prev 9-days'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tbar91sq',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Quadratic (tbar91^2)/30'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tbars',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Average temperature Capture day Sensor'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tbars90',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='tbars over 9-day forward from capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tbars91',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='tbars over 9-day backward from capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tbars92',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='tbars over 9-day backward, starting 9-days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tbars93',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='tbars over 9-day backward, starting 18-days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tbars94',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='tbars over 9-day backward, starting 27-days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='umt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Equals 1 if uterus empty, zero if full'),
        ),
    ]
