# Generated by Django 2.1.4 on 2019-05-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRAP', '0002_auto_20190502_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsetse',
            name='capture_month_of_year_cctem',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='date_sample_collected_datecap',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='date_sample_started_datest',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='day_of_the_year_9_day_pool_dofy9',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='day_of_the_year_dofy',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='days_delay_in_dissection_del',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='estimated_age_negative_changed_to_0_age0',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='full_term_ppp_pregnant_etc_ftpp',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='full_term_ppp_pregnant_etc_ftppp',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='full_term_ppp_pregnant_etc_ppall',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='log_10_of_haematin_in_nanograms_log10hm',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='methods_pooled_major_mdpall',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='mother_plus_pupa_dry_weight_mg_totdwmg',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='mother_plus_pupa_fat_weight_mg_totfatmg',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='mother_plus_pupa_resid_dry_weight_mg_totrdwmg',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='mothers_abdominal_resid_dry_weight_mg_ardwmg',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='mothers_dry_weight_mg_dwmg',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='mothers_fat_weight_mg_fatmg',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='mothers_thoracic_resid_dry_weight_mg_trdwmg',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='newpage_numbering_pgall',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='ovcat_where_ppp_files_with_u_0_put_into_next_ovcat_cnu',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='puparial_dry_weight_mg_dwpmg',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='puparial_fat_weight_mg_fatpmg',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='puparial_fresh_weight_mg_fwpmg',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='puparial_resid_dry_weight_mg_rdwpmg',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='pyriproxyfen_traps_or_targets_used_pyri',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='residual_dry_weight_mg_rdwmg',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='sperm_left_plus_right_slr',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='total_sperm_pooled_0_1to8_9to16_17to20',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='total_sperm_pooled_units_4_slrp',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='unique_number_for_each_fly_in_file_idfly',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='wing_length_wlmm',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='year_of_dissection_dy',
        ),
        migrations.AddField(
            model_name='tsetse',
            name='age0',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Methods max pooling nkl'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ardwmg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mothers abdominal resid. dry weight (mg)'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='cctem',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Capture month of year'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='cnu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ovcat where ppp flies with u=0 put into next ovcat'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='datecap',
            field=models.DateField(blank=True, null=True, verbose_name='Date sample collected'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='datest',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Date sample started'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='del1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Days delay in dissection'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='dofy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Day of the year'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='dofy9',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Day of the year: 9-day pool'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='dwmg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mothers dry weight (mg)'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='dwpmg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puparial dry weight (mg)'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='dy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Year of dissection'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='fatmg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mothers fat weight (mg'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='fatpmg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puparial fat weight (mg)'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ftpp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Full term, ppp, pregnant etc'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ftppp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Full term, ppp, pregnant etc'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='fwpmg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puparial fresh weight (mg)'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='idfly',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unique number for each fly in file'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='log10hm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='log10 of haematin in nanograms'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='mdpall',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Methods pooled major'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='pgall',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='New page numbering'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ppall',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Full term, ppp, pregnant etc'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='pyri',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pyriproxyfen traps/targets used'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='rdwmg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Residual dry weight (mg)'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='rdwpmg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puparial resid. dry weight (mg)'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='slr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sperm: left plus right'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='slrp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Total sperm: pooled units 4'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='slrp2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tot sperm: pooled 0, 1-8, 9-16, 17-20'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='totdwmg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mother+pupa dry weight (mg)'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='totfatmg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mother+pupa fat weight (mg)'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='totrdwmg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mother+pupa resid. dry weight (mg)'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='trdwmg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mothers thoracic resid. dry weight (mg'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='wlmm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Wing length (mm)'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='birth_month_bm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Methods max pooling nkl'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='birth_month_different_definition_from_bm_bm2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Methods max pooling nkl'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='birth_month_for_female_born_in_month_cms_bms',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Methods max pooling nkl'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='birth_year_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Methods max pooling nkl'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='cf56',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ovarian category where flies recategorised if f>4'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='cf6',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ovarian category where flies recategorised if f>5'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='ctemp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ovarian age moving c = 4-7 to 8-11 if f>4'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='ndvi',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True, verbose_name='NDVI on day of capture'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='ndvi300',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True, verbose_name='NDVI Average over 30-days forward from capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='ndvi301',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True, verbose_name='NDVI Average over 30-days backward from capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='ndvi302',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True, verbose_name='NDVI Average over 30-days backward, starting 30 days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='ndvi303',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True, verbose_name='NDVI Average over 30-days backward, starting 60 days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='ndvi90',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True, verbose_name='NDVI Average over 9-days forward from capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='ndvi91',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True, verbose_name='NDVI Average over 9-days backward from capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='ndvi92',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True, verbose_name='NDVI Average over 9-days backward, starting 9 days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='ndvi93',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True, verbose_name='NDVI Average over 9-days backward, starting 18 days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='ndvi94',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=25, null=True, verbose_name='NDVI Average over 9-days backward, starting 27 days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='pooled_capture_methods_mdp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Methods max pooling nkl'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='pooled_capture_sites_sitep',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Methods max pooling nkl'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='rain',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Total rain on day of capture'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tbar',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Average of max and min temp on day of capture'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tbar90',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Tbar Average over 9-days forward from capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tbar91',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Tbar Average over 9-days backward from capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tbar92',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Tbar Average over 9-days backward, starting 9 days prior to capture day '),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tbar93',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Tbar Average over 9-days backward, starting 18 days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tbar94',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Tbar Average over 9-days backward, starting 27 days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tmax',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Maximum temp on day of capture'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tmax90',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Tmax Average over 9-days forward from capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tmax91',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Tmax Average over 9-days backward from capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tmax92',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Tmax Average over 9-days backward, starting 9 days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tmax93',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Tmax Average over 9-days backward, starting 18 days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tmax94',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Tmax Average over 9-days backward, starting 27 days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tmin',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Minimum temp on day of capture'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tmin90',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Tmin Average over 9-days forward from capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tmin91',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Tmin Average over 9-days backward from capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tmin92',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Tmin Average over 9-days backward, starting 9 days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tmin93',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Tmin Average over 9-days backward, starting 18 days prior to capture day'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tmin94',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Tmin Average over 9-days backward, starting 27 days prior to capture day'),
        ),
    ]
