# Generated by Django 2.1.4 on 2019-05-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRAP', '0003_auto_20190503_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsetse',
            name='alphanumeric_label_for_tube',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='birth_month_bm',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='birth_month_different_definition_from_bm_bm2',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='birth_month_for_female_born_in_month_cms_bms',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='birth_year_by',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='capture_day_of_month',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='capture_days_since_01011960',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='capture_end_time',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='capture_method_code',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='capture_month_of_experiment_cms',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='capture_month_year',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='capture_sites',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='capture_start_time',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='capture_year',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='caseno2',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='cut_off_al_length_for_deciding_if_fly_aborted',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='determinant_for_pregnancy_stage',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='disector_code',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='dissection_day',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='dissection_month',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='error_code_1',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='error_code_2',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='estimated_age_days',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='estimated_birth_day_julian',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='estimated_day_of_pregnancy',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='estimated_mother_plus_pupa_dry_weight_etotdw',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='estimated_mother_plus_pupa_fat_weight_etotfat',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='estimated_mother_plus_pupa_resid_dry_weight_etotrdw',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='experimental_month',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='hunger_stage',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='inter_larval_period',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='largest_ooctye_diameter_mm_x100',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='largest_ooctye_length_mm_x100',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='left_spermatophore_content_0_to_10',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='microscope',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='mother_plus_pupa_dry_weight',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='mother_plus_pupa_fat_weight',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='mother_plus_pupa_resid_dry_weight',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='mother_plus_pupa_totfat0',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='mother_thorasic_residue_dry_weight',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='mothers_abdominal_resid_dry_weight',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='mothers_dry_weight',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='mothers_fat_weight',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='mothers_haematin',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='mothers_resid_dry_weight',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='number_on_page',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='ovarian_category',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='page',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='percent_pregnancy_completed',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='pooled_capture_methods_mdp',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='pooled_capture_sites_sitep',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='presence_of_adult_mx',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='presence_of_pupa_px',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='pteridine',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='puparial_dry_weight_dwp',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='puparial_dry_weight_est_from_volume_edwp',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='puparial_fat_weight_corrected_for_process_delay_fatp0',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='puparial_fat_weight_est_from_volume_efatp',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='puparial_fat_weight_fatp',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='puparial_fresh_weight_est_from_volume_efwp',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='puparial_fresh_weight_fwp',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='puparial_length_mm_x100_dpm',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='puparial_length_mm_x100_lpm',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='puparial_resid_dry_weight_est_from_volume_erdwp',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='puparial_resid_dry_weight_rdwp',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='r_is_1_if_disector_noted_a_problem_r_is_0_otherwise',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='right_spermatophore_content_0_to_10',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='second_largest_ooctye_length_mm_x100',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='time_of_disection_am_or_pm',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='tube_number',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='uterine_content',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='uterine_dry_weight_est_from_volume',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='uterine_fat_weight_est_from_volume',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='uterine_fresh_weight_est_from_volume',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='uterine_length_udm_mm_x100',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='uterine_length_ulm_mm_x100',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='uterine_resid_dry_weight_est_from_volume',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='uterine_volume',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='uterine_volume_volp',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='wing_fray_1_to_6',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='wing_length_mm_x100_wlm',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='wing_length_mm_x100_wlm2',
        ),
        migrations.RemoveField(
            model_name='tsetse',
            name='wing_length_scale_wl',
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ad',
            field=models.IntegerField(blank=True, null=True, verbose_name='ad Largest oocyte diameter - mm x 100'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estimated age - days'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='al',
            field=models.IntegerField(blank=True, null=True, verbose_name='al Largest oocyte length - mm x 100'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='alm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cut-off al length for deciding if fly aborted'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ardw',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mothers abdominal resid. dry weight'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='bd',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='bd 2nd largest oocyte diameter - mm x 100'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='bday',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estimated birth day - Julian'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='bl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='bl 2nd largest oocyte diameter -mm x 100'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='bm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Birth month'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='bm2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Birth month??? Different definition from bm: check'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='bms',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Birth month for female born in month cms CAREFUL'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Birth year'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='c',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ovarian Category'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='caseno',
            field=models.IntegerField(blank=True, null=True, verbose_name='caseno2'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='cd',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capture day of month'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capture month of year'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='cms',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Capture month of experiment'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='cy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capture Year'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='d',
            field=models.IntegerField(blank=True, null=True, verbose_name='Determinant for pregancy stage'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='dayj',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capture days since 01-01-1960'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='dd',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dissection day'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='di',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dissector Code'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='dm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dissection month'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='dpm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puparial length - mm x 100'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='dw',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mothers dry weight'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='dwp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puparial dry weight'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='e1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Error code 1'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='e2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Error code 2'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='edwp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puparial dry weight - est. from volume'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='edwu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uterine dry weight - est. from volume'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='efatp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puparial fat weight - est. from volume'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='efatu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uterine fat weight - est. from volume'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='efwp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puparial fresh weight - est. from volume'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='efwu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uterine fresh weight - est. from volume'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='erdwp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puparial resid. dry weight - est. from volume'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='erdwu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uterine resid. dry weight - est. from volume'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='etotdw',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estimated mother+pupa dry weight'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='etotfat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estimated mother+pupa fat weight'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='etotrdw',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estimated mother+pupa resid. dry weight'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='expmon',
            field=models.IntegerField(blank=True, null=True, verbose_name='Experimental Month'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='f',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wing fray 1-6'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='fat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mothers fat weight'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='fatp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puparial fat weight'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='fatp0',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puparial fat weight - corrected for process delay'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='fwp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puparial fresh weight'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='h',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hunger stage'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='haem',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mothers haematin'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ilp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Inter-larval period'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='lpm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puparial length - mm x 100'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='m',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Microscope'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='md',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capture Method code'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='mdp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pooled capture methods'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='mk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mark'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='mx',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Presence of adult'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number on page'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='pd',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estimated day of pregnancy'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='pg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Page'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ppr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Percent pregnancy completed'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='pt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pteridine???'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='px',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Presence of pupa'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='r',
            field=models.IntegerField(blank=True, null=True, verbose_name='r=1 if dissector has noted problem, r=0 otherwise'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='rdw',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mothers resid. dry weight'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='rdwp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puparial resid. dry weight'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='site',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Capture Sites'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='sitep',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pooled Capture sites'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='sl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Left spermatophore content 0-10'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='sr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Right spermatophore content 0-10'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='t',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time of dissection - am/pm'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tend',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Capture end time'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='totdw',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mother+pupa dry weight'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='totfat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mother+pupa fat weight'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='totfat0',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mother+pupa ??????'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='totrdw',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mother+pupa resid. dry weight'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='trdw',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mothers thoracic resid. dry weight'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tst',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Capture start time'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tube',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tube number'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='tubet',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alphanumeric label for tube'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='u',
            field=models.IntegerField(blank=True, null=True, verbose_name='uterine content'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='udm',
            field=models.IntegerField(blank=True, null=True, verbose_name='udm Uterine length - mm x 100'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='ulm',
            field=models.IntegerField(blank=True, null=True, verbose_name='ulm Uterine length - mm x 100'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='vol',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uterine volume'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='volp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uterine volume'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='wl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wing length - scale'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='wlm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wing length - mm x 100'),
        ),
        migrations.AddField(
            model_name='tsetse',
            name='wlm2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wing length - mm x 100'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='age0',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estimated age - negatives changed to 0 '),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='bt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BT'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='dwu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='DWU'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='facwlmnew',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='facwlmnew'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='fatu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FATU'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='fwu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FWU'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='genus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Genus'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='idd',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='rdwu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RDWU'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='sex',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='tr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TR'),
        ),
        migrations.AlterField(
            model_name='tsetse',
            name='vpn',
            field=models.IntegerField(blank=True, null=True, verbose_name='vpn'),
        ),
    ]
